$(function(){
	$("input[type=button]").click(function(){
		$.ajax({
			url:"checkuser",
			type:"post",
			data:{
				//"id":$("#id").val(),
				//format:"json"
			},
			dataype:"JSON",
			success:function(data){
				$("#content").text(data);
			},
			error:function(){
				alert("失败");
			}
		});
	});
});